/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post115, git sha1 b5170e139) */

(* top =  1  *)
(* src = "/home/runner/work/ttihp-verilog-test/ttihp-verilog-test/src/design.py:11" *)
(* generator = "Amaranth" *)
module top(rst, led, clk);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  wire [24:0] \$1 ;
  reg [23:0] \$2 ;
  (* src = "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/amaranth/hdl/_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "/home/runner/work/ttihp-verilog-test/ttihp-verilog-test/src/design.py:12" *)
  reg [23:0] cnt = 24'h000000;
  (* src = "/home/runner/work/ttihp-verilog-test/ttihp-verilog-test/src/design.py:8" *)
  output led;
  wire led;
  (* src = "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/amaranth/hdl/_ir.py:283" *)
  input rst;
  wire rst;
  assign \$1  = cnt + (* src = "/home/runner/work/ttihp-verilog-test/ttihp-verilog-test/src/design.py:13" *) 2'h2;
  (* src = "/home/runner/work/ttihp-verilog-test/ttihp-verilog-test/src/design.py:12" *)
  always @(posedge clk)
    cnt <= \$2 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$2  = \$1 [23:0];
    if (rst) begin
      \$2  = 24'h000000;
    end
  end
  assign led = cnt[23];
endmodule
