name: docs

on:
  push:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install uv
        shell: bash
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv sync

      - name: Generate Verilog from Amaranth
        run: |
          uv run main.py
          echo "Generated  from main.py"

      - name: Build docs
        uses: TinyTapeout/tt-gds-action/docs@ttihp25b
